version: "3"
services:
  webappp:
    build: ./flask/
    image: webapp:latest
    ports:
      - "5000:5000"
    container_name: webappp
    networks:
      app:
        ipv4_address: 172.20.0.6
    depends_on:
      - generative
      - language
      - deepspeech
  generative:
    build: ./model_functions/generative
    image: generative:latest
    container_name: generative
    networks:
      app:
        ipv4_address: 172.20.0.2
    ports:
      - "5002:5002"
  language:
    build: ./model_functions/language
    image: language:latest
    container_name: language
    networks:
      app:
        ipv4_address: 172.20.0.3
    ports:
      - "5003:5003"
  deepspeech:
    build: ./model_functions/language/deepspeech
    image: deepspeech:latest
    container_name: deepspeech
    networks:
      app:
        ipv4_address: 172.20.0.5
    ports:
      - "5005:5005"

networks:
  app:
    ipam:
      config:
        - subnet: 172.20.0.0/24
