version: "3"
services:
  webappp:
    build: ./flask/
    image: eu.gcr.io/ml-webpage-264418/webapp:latest
    restart: unless-stopped
    ports:
      - "443:443"
    container_name: webappp
    networks:
      app:
        ipv4_address: 172.20.0.6
    depends_on:
      - generative
      - language
      - deepspeech
      - certbot
    volumes:
      - certconf:/etc/letsencrypt
      - certwww:/var/www/certbot

  certbot:
    image: certbot/dns-cloudflare

    restart: unless-stopped
    volumes:
      - certconf:/etc/letsencrypt
      - certwww:/var/www/certbot
      - ./logs:/var/log/letsencrypt
      - /Users/timgretler/projects/ml-webpage/ml-webpage/cloudflare.ini:/cloudflare.ini
    command: certonly --dns-cloudflare  --dns-cloudflare-credentials /cloudflare.ini --email exaple@gmail.com --server https://acme-v02.api.letsencrypt.org/directory -d *.example.com

  generative:
    build: ./model_functions/generative
    image: eu.gcr.io/ml-webpage-264418/generative:latest
    container_name: generative
    networks:
      app:
        ipv4_address: 172.20.0.2
    ports:
      - "5002:5002"
  language:
    build: ./model_functions/language
    image: eu.gcr.io/ml-webpage-264418/language:latest
    container_name: language
    networks:
      app:
        ipv4_address: 172.20.0.3
    ports:
      - "5003:5003"
  deepspeech:
    build: ./model_functions/language/deepspeech
    image: eu.gcr.io/ml-webpage-264418/deepspeech:latest
    container_name: deepspeech
    networks:
      app:
        ipv4_address: 172.20.0.5
    ports:
      - "5005:5005"

networks:
  app:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  certconf:
  certwww:
